### PR TITLE
Feat/user story two

### PR DESCRIPTION
**Pull request by z-prince**
Complete user story two by adding a new application link to pets index and redirecting to the new app's show page.

### CODE REVIEW

**Comment by CoryBethune** [comment]
1) Does the form on the application new view page need to show the status? I think that's superfluous information since only we would be modifying/manipulating that column value. What is your opinion on this?

2) I'm not seeing where you have created the view for the application show and we will need tests for it as well.

**Comment by CoryBethune** [comment]
I see what you are doing with the status field on the form. Why not just change those render tags into regular <%> tags so they aren't displayed to the user but that status update is still carried over to params.

**Comment by z-prince** [comment]
> I see what you are doing with the status field on the form. Why not just change those render tags into regular <%> tags so they aren't displayed to the user but that status update is still carried over to params.

Done!

**Comment by CoryBethune** [comment]
Awesome. Great job!

**Pull request merged**
